/**
 * PurgeCSS — 사용되지 않는 CSS 제거 (테마 PHP/마크업 기준)
 * 실행: npm run purgecss → assets/css/style.css 덮어쓰기 후, php build-css.php 로 미니파이
 */
module.exports = {
  content: [
    './**/*.php',
  ],
  css: ['./assets/css/style.css'],
  output: './assets/css/style.css',
  variables: true,
  keyframes: true,
  safelist: {
    standard: [
      'toggled',
      'header-scrolled',
      'header-at-top',
      'copied',
      'della-is-front',
      'lawyer-list-page',
      'lawyer-profile-page',
      'response-board-page',
      'success-cases-page',
      'home',
      'blog',
      'front-page',
      'single',
      'page',
      'archive',
      'search',
      'error404',
      'admin-bar',
      'logged-in',
      'no-customize-support',
      'custom-background',
      'wp-custom-logo',
      'page-template',
      'page-template-default',
      'attachment',
      'paged',
      'single-paged',
      'widget',
      'widget-title',
      'comment-body',
      'comment-meta',
      'comment-author',
      'vcard',
      'fn',
      'comment-metadata',
      'edit-link',
      'comment-content',
      'reply',
      'notice',
      'notice-info',
      'is-dismissible',
      'della-seo-monitoring-notice',
      'current-menu-item',
      'current_page_item',
      'current-menu-ancestor',
      'screen-reader-text',
      'sticky',
      'hentry',
      'entry-content',
      'entry-header',
      'entry-title',
      'entry-summary',
      'alignleft',
      'alignright',
      'aligncenter',
      'wp-caption',
      'wp-caption-text',
      'gallery',
      'gallery-caption',
      'has-sidebar',
      'one-column',
      'two-column',
      'right-sidebar',
      'left-sidebar',
      'menu-item',
      'menu-item-has-children',
      'sub-menu',
      'nav-menu',
      'primary-menu',
    ],
    deep: [
      /^page-id-/,
      /^postid-/,
      /^post-type-/,
      /^term-/,
      /^wp-block-/,
      /^has-/,
      /^align/,
      /^size-/,
      /^wp-image-/,
    ],
    greedy: [
      /^comment/,
      /^widget/,
      /^entry-/,
      /^nav-/,
      /^menu/,
      /^current/,
      /^screen-reader/,
    ],
  },
};
